--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Debian 15.13-1.pgdg120+1)
-- Dumped by pg_dump version 15.13 (Debian 15.13-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Artists; Type: TABLE; Schema: public; Owner: rockola_user
--

CREATE TABLE public."Artists" (
    "ArtistId" integer NOT NULL,
    "Name" text NOT NULL,
    "Rp" integer NOT NULL,
    "Picture" text NOT NULL
);


ALTER TABLE public."Artists" OWNER TO rockola_user;

--
-- Name: Artists_ArtistId_seq; Type: SEQUENCE; Schema: public; Owner: rockola_user
--

ALTER TABLE public."Artists" ALTER COLUMN "ArtistId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Artists_ArtistId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: PlaylistItems; Type: TABLE; Schema: public; Owner: rockola_user
--

CREATE TABLE public."PlaylistItems" (
    "Id" integer NOT NULL,
    "SongName" text NOT NULL,
    "SongPath" text NOT NULL,
    "AddedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."PlaylistItems" OWNER TO rockola_user;

--
-- Name: PlaylistItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: rockola_user
--

ALTER TABLE public."PlaylistItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."PlaylistItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Songs; Type: TABLE; Schema: public; Owner: rockola_user
--

CREATE TABLE public."Songs" (
    "SongId" integer NOT NULL,
    "Name" text NOT NULL,
    "Path" text NOT NULL,
    "Rp" integer NOT NULL,
    "ArtistName" text NOT NULL
);


ALTER TABLE public."Songs" OWNER TO rockola_user;

--
-- Name: Songs_SongId_seq; Type: SEQUENCE; Schema: public; Owner: rockola_user
--

ALTER TABLE public."Songs" ALTER COLUMN "SongId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Songs_SongId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: rockola_user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO rockola_user;

--
-- Data for Name: Artists; Type: TABLE DATA; Schema: public; Owner: rockola_user
--

COPY public."Artists" ("ArtistId", "Name", "Rp", "Picture") FROM stdin;
1	3030	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\3030\\portada.jpg
2	Alejandro Sanz	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz\\portada.jpg
3	Alemán	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alemán - Noviembre\\portada.jpg
4	Alex Pires	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alex Pires\\portada.jpg
5	Andrés Calamaro	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Andrés Calamaro\\portada.jpg
6	Angela Aguilar	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar\\portada.jpg
7	Bellakath	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath\\portada.jpg
8	Bizarrap	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bizarrap\\portada.jpg
9	Camilo	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Camilo\\portada.jpg
10	Carin Leon	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon\\portada.jpg
11	Christian Nodal	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico\\portada.jpg
12	Conjunto el Golpe	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Conjunto el Golpe\\portada.jpg
13	Edén Muñoz	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz\\portada.jpg
14	El Komander	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\El Komander\\portada.jpg
15	Enigma Norteño	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Enigma Norteño\\portada.jpg
16	Eros Ramazzotti	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Eros Ramazzotti\\portada.jpg
17	Greeicy	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Greeicy\\portada.jpg
18	Grupo Firme	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme\\portada.jpg
19	Grupo Frontera	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Frontera\\portada.jpg
20	Grupo Maximo Grado	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Maximo Grado\\portada.jpg
21	Hombres G	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Hombres G\\portada.jpg
22	Jey	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Jey\\portada.jpg
23	Joaquín Sabina	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Joaquín Sabina\\portada.jpg
24	Junior H	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H\\portada.jpg
25	Kany Garcia	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Kany Garcia\\portada.jpg
26	KAROL G	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\KAROL G\\portada.jpg
27	Lary	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Lary\\portada.jpg
28	lil joujou	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\lil joujou\\portada.jpg
29	LK	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK\\portada.jpg
30	Luis R Conriquez	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez\\portada.jpg
31	Mau y Ricky	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Mau y Ricky\\portada.jpg
32	MC Marks	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\MC Marks\\portada.jpg
33	Panter Bélico	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa\\portada.jpg
34	Pepe Aguilar	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Pepe Aguilar - Celebrando a México\\portada.jpg
35	Peso Pluma	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Peso Pluma\\portada.jpg
36	Piso 21	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Piso 21\\portada.jpg
37	Potencia Lirical	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Potencia Lirical\\portada.jpg
38	Raillow	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Raillow\\portada.jpg
39	Ramoncito Vega	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ramoncito Vega\\portada.jpg
40	Residente	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Residente\\portada.jpg
41	Ricardo Arjona	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona\\portada.jpg
42	Ricky Martin	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricky Martin\\portada.jpg
43	Santa Fe Klan	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Santa Fe Klan\\portada.jpg
44	Steve Aoki	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Steve Aoki\\portada.jpg
45	Tainy	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Tainy\\portada.jpg
46	Thalia	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Thalia\\portada.jpg
47	Travis Scott	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Travis Scott\\portada.jpg
48	Tília	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Tília\\portada.jpg
49	Wisin	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Wisin\\portada.jpg
50	Young Miko	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Young Miko\\portada.jpg
51	Yuridia	0	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Yuridia\\portada.jpg
\.


--
-- Data for Name: PlaylistItems; Type: TABLE DATA; Schema: public; Owner: rockola_user
--

COPY public."PlaylistItems" ("Id", "SongName", "SongPath", "AddedAt") FROM stdin;
\.


--
-- Data for Name: Songs; Type: TABLE DATA; Schema: public; Owner: rockola_user
--

COPY public."Songs" ("SongId", "Name", "Path", "Rp", "ArtistName") FROM stdin;
1	Longa Estrada.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\3030	0	3030
2	Bio.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz	0	Alejandro Sanz
3	Contigo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz	0	Alejandro Sanz
4	Correcaminos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz	0	Alejandro Sanz
5	Iba.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz	0	Alejandro Sanz
6	Mares De Miel.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz	0	Alejandro Sanz
7	Yo No Quiero Suerte.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz	0	Alejandro Sanz
8	Azúcar En Un Bowl.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
9	Back In The City.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
10	El Trato.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
11	Este Segundo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
12	It_s OK.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
13	Los Lugares.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
14	Mi Persona Favorita.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
15	No Tengo Nada.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
16	Te Canto Un Son (Mezcla Binaural).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
17	Te Canto Un Son.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #ELDISCO	0	Alejandro Sanz
18	#LaGira Intro (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
19	#LaGira Outro (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
20	Aquello Que Me Diste (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
21	Azúcar En Un Bowl (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
22	Back In The City (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
23	Capitán Tapón (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
24	Corazón Partío (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
25	Deja Que Te Bese (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
26	El Trato (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
27	En La Planta De Tus Pies _ Donde Convergemos _ A La Primera Persona (Medley _ En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
28	Hoy Que No Estás (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
29	La Peleíta _ El Tren De Los Momentos (Medley _ En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
30	Lo Que Fui Es Lo Que Soy (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
31	Looking For Paradise (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
32	Los Lugares (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
33	Mi Marciana (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
34	Mi Persona Favorita (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
35	No Tengo Nada (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
36	Quisiera Ser (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
37	Te Canto Un Son (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
38	Y, ¿Si Fuera Ella_ _ Amiga Mía _ Mi Soledad Y Yo (Medley _ En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
39	Yo Sé Lo Que La Gente Piensa _ ¿Lo Ves_ (Medley _ En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
40	Yo Te Traigo…20 Años (En Directo En El Wanda Metropolitano _ Madrid _ 2019).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - #LAGIRA de #ELDISCO	0	Alejandro Sanz
41	Cuándo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Correcaminos EP	0	Alejandro Sanz
42	Volé.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Correcaminos EP	0	Alejandro Sanz
43	Amiga mía.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
44	Aprendiz (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
45	Corazón partío.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
46	Cuando nadie me ve (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
47	Cómo te echo de menos (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
48	Lo que fui es lo que soy (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
49	Quiero morir en tu veneno (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
50	Quisiera ser (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
51	Se le apagó la luz.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
52	Siempre es de noche (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
53	Toca para mí.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
54	Todo es de color (Unplugged).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
55	Y sólo se me ocurre amarte.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - MTV Unplugged	0	Alejandro Sanz
56	Amiga mía (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
57	Amiga mía (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
58	Amiga mía (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
59	Antes que nada amigos (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
60	Aprendiz (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
61	Aquello que me diste (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
62	Aquello que me diste (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
63	Aquello que me diste (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
64	Aquello que me diste.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
65	Corazón partío (Concierto Buenos Aires Luna Park 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
66	Corazón partío (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
67	Corazón partío (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
68	Corazón partío (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
69	Donde quiera que estés (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
70	Es algo personal (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
71	Ese último momento (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
72	Ese último momento (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
73	Ese último momento (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
74	Ese último momento.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
75	Hoy que no estás (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
76	Hoy que no estás (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
77	Hoy que no estás (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
78	Hoy que no estás.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
79	Intro (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
80	La margarita dijo no (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
81	La margarita dijo no (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
82	La margarita dijo no (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
83	La margarita dijo no.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
84	Si hay Dios... (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
85	Si hay Dios... (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
86	Si hay Dios... (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
87	Si hay Dios.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
88	Siempre es de noche (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
89	Siempre es de noche (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
90	Siempre es de noche.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
91	Un charquito de estrellas (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
92	Un charquito de estrellas (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
93	Un charquito de estrellas (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
94	Un charquito de estrellas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
95	Y, ¿Si fuera ella_ (Concierto Tour Más 98).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
96	Y, ¿Si fuera ella_ (Instrumental con coros).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
97	Y, ¿Si fuera ella_ (Maqueta).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
98	Y, ¿Si fuera ella_.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Más_ 20 Aniversario	0	Alejandro Sanz
99	Geometría.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sanz	0	Alejandro Sanz
100	La Rosa.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sanz	0	Alejandro Sanz
101	No Sé Qué Me Pasas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sanz	0	Alejandro Sanz
102	Si Yo Quisiera Y Si Tú Pudieras.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sanz	0	Alejandro Sanz
103	Uno Nada Más.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sanz	0	Alejandro Sanz
104	Y Ya Te Quería.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sanz	0	Alejandro Sanz
105	A Mí No Me Importa.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
106	A Que No Me Dejas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
107	Capitán Tapón.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
108	El Club De La Verdad.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
109	El Silencio De Los Cuervos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
110	La Guarida Del Calor.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
111	La Vida Que Respira.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
112	No Madura El Coco.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
113	Pero Tú.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
114	Suena La Pelota.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
115	Todo Huele A Ti.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
116	Tú La Necesitas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
117	Un Zombie A La Intemperie.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alejandro Sanz - Sirope	0	Alejandro Sanz
118	Close Friends (feat. Cozy Cuz).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alemán - Noviembre	0	Alemán
119	Do Tipo Esnobe.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alex Pires	0	Alex Pires
120	Inconsequente.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alex Pires	0	Alex Pires
121	Me Ouça.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alex Pires	0	Alex Pires
122	Nosso Mundo (Live).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Alex Pires	0	Alex Pires
123	Flaca.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Andrés Calamaro	0	Andrés Calamaro
124	Piensa en Mí.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar	0	Angela Aguilar
125	Contigo En La Distancia.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
126	Luna Lunera.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
127	Obsesión.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
128	Piel Canela.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
129	Quizás Quizás Quizás.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
130	Solamente Una Vez.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
131	Somos Novios.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
132	Toda Una Vida.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Angela Aguilar - Bolero	0	Angela Aguilar
133	BWS (feat. Alfa Mb, Matt Vargas, Dj Yaso & Alexito Mix) (Remix).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
134	Cumbiatronik.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
135	Cupido Malo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
136	Diabla (feat. Dj Foxy, Kery, Luis Gleez, Dj Yaso, Brayan Morales).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
137	El Bmw.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
138	Fabulosa de Paris.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
139	Flow Alta Gama.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
140	Flow Calle (feat. Razieel, Alexito Mix & Brayan Morales).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
141	Gatita.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
142	La abogada.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
143	La Gata de la Agrícola Oriental (feat. Kery).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
144	Lluvia De Micheladas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
145	MAMI CHAKALOSA.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
146	Me le pegue (feat. Daizak).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
147	Mi Adelita (feat. Kery, Luis Gleez, Matt Vargas, Brayan Morales, Dj Yaso & DJ Fox).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
148	Papi Quiero Perrear.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
149	Se Va (feat. Noriega, Leinvd & La Mafia del Perreo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
150	Sonido Bellako.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
151	Y Yo Me Le Pego.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath	0	Bellakath
152	911 (feat. Brayan Morales).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - 911	0	Bellakath
153	Intro Old School (feat. Dj Yaso).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - 911	0	Bellakath
154	Policia Del Perreo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - 911	0	Bellakath
155	Prendelo (feat. Kery).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - 911	0	Bellakath
156	R9 Aleteo (feat. Dj Yaso).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - 911	0	Bellakath
157	Se Alborota (feat. Profeta Yao Yao, Alu Mix & Dj Bryan Kingz).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - 911	0	Bellakath
158	A Ese Gato.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
159	Es tu culpa.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
160	Gata Gabbana.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
161	Gatita (Guaratech version).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
162	Intro.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
163	Kitty Culea.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
164	Kittyponeando (interlude).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
165	Kittyponeo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
166	Minina.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
167	Para la gata que quiere un chakal (interlude).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
168	Pekorita Love.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
169	Que tu quiere.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
170	Quiero Fumar (Remix).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
171	Reggaeton Champagne.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
172	Tres Deseos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
173	Tuma.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
174	Y Cuando Queme.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bellakath - Kittyponeo	0	Bellakath
175	Young Miko_ Bzrp Music Sessions, Vol. 58.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Bizarrap	0	Bizarrap
176	NASA.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Camilo	0	Camilo
177	Ron Con Coca.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon	0	Carin Leon
178	Te quiero.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon	0	Carin Leon
179	The One (Pero No Como Yo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon	0	Carin Leon
180	Arcoíris de Papel (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
181	Bonita y Mala (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
182	Cariñito de Mi Vida (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
183	Con Olor a Hierba (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
184	Contigo o Sin Ti (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
185	Cuéntame Tus Penas (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
186	El Indio Enamorado (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
187	En la Barra (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
188	La Boda del Huitlacoche (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
189	La Mesa del Rincón (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
190	Ni en el Mundo Te Hago (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
191	Ni Parientes Somos (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
192	No Llores Mas (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
193	Para No Verte Mas (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
194	Para Que Regreses (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
195	Popurrí de Cumbias (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
196	Sublime Mujer (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
197	Te Fuiste Paloma Blanca (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
198	Tu Ingratitud (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
199	Volví a Nacer (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Carin Leon - Borrachera Con Los Honorables (En Vivo)	0	Carin Leon
200	Adiós Amor.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
201	Amantes Prohibidos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
202	Aquí Abajo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
203	De Los Besos Que Te Di.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
204	Entre El Amar Y El Querer.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
205	Eres.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
206	Me Dejé Llevar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
207	Mi Persona Preferida.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
208	No Te Contaron Mal.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
209	Olvídate De Mí.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
210	Probablemente.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
211	Qué Culpa Tiene Él.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
212	Se Me Olvidó.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
213	Seremos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
214	Si No Es Muy Tarde (Versión Mariachi).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
215	Si Te Falta Alguien.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
216	Te Fallé.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
217	Te Quise Olvidar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
218	Viajes Para Marte.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
219	¿Por Qué Dejaste Que Te Amara_.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Duelo Romántico	0	Christian Nodal
220	Amor Tóxico.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
221	AYAYAY!.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
222	Botella Tras Botella.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
223	Dime Cómo Quieres.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
224	Nace Un Borracho.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
225	Nada Nuevo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
226	Si Usted Fuera Yo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
227	Te Voy A Olvidar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
228	Vas A Querer Regresar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
229	¿Quién Es Usted_.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - La Voz De México ¡Lo Mejor!	0	Christian Nodal
230	Así O Más Claro.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
231	Aunque Me Haga Daño.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
232	Aunque Sea A Escondidas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
233	El Bato De Tu Vida.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
234	Lo Más Seguro.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
235	Porque Tú Llegaste.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
236	Soy El Mismo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
237	Te Quiero Mil.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
238	Una Amante.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
239	Vuelvo A Fingir.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - Lo Mejor De Dos Grandes	0	Christian Nodal
240	Acá Entre Nos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - México en Mi Voz	0	Christian Nodal
241	La Ley del Monte.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - México en Mi Voz	0	Christian Nodal
242	La Media Vuelta.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - México en Mi Voz	0	Christian Nodal
243	Mujeres Divinas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - México en Mi Voz	0	Christian Nodal
244	Ya Lo Sé Que Tú Te Vas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Christian Nodal - México en Mi Voz	0	Christian Nodal
245	Dinastía Aguilar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Conjunto el Golpe	0	Conjunto el Golpe
246	Como En Los Viejos Tiempos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz	0	Edén Muñoz
247	Me Aventé.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz	0	Edén Muñoz
248	MONEY EDITION.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz	0	Edén Muñoz
249	Alias Jabón.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
250	Bye Bye.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
251	Cómo Estás Tú.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
252	El Mikima.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
253	El Que Quiere Puede.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
254	El Viejo del Monte.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
255	En el Pedir Está el Dar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
256	Hotel el Cid.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
257	La Nena.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
258	Le Pasé a la Plebe.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
259	Peca de Bonita.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
260	Prometiste.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
261	Pudiste Pero No Quisiste.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
262	Que la Dejen Ir al Baile Sola.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
263	Rosas Blancas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
264	Sueño Güajiro.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
265	Suéltame la Mano.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Edén Muñoz - Como en los Viejos Tiempos	0	Edén Muñoz
266	Una Noche En Culiacán.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\El Komander	0	El Komander
267	El Cabezón (El Papas Fritas).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Enigma Norteño	0	Enigma Norteño
268	Sono.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Eros Ramazzotti	0	Eros Ramazzotti
269	Soy.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Eros Ramazzotti	0	Eros Ramazzotti
270	Lejos Conmigo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Greeicy	0	Greeicy
271	Aquí No Se Termina (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
272	Ayúdame A Creer (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
273	Blindajes Peña (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
274	Cariñito (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
275	Dile (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
276	El Chube (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
277	Hice (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
278	La Historia De Mis Manos (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
279	Le Creí (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
280	Perdón (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
281	Prohibido (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
282	Soy Un Diez (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
283	Suspiros (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
284	Te Estaré Esperando (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
285	Te Soñé (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
286	Te Vas Amor (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
287	Valió La Pena Equivocarme (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
288	Ya Lo Sé - Acá Entre Nos (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
289	¿Dónde Estás Presumida_ (En Vivo).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Firme	0	Grupo Firme
290	Quédate Bebé.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Frontera	0	Grupo Frontera
291	Ya Pedo Quién Sabe.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Frontera	0	Grupo Frontera
292	Ni Tan Diablo Ni Tan Santo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Grupo Maximo Grado	0	Grupo Maximo Grado
293	Te quiero.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Hombres G	0	Hombres G
294	Obrigada.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Jey	0	Jey
295	Y Nos Dieron las Diez.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Joaquín Sabina	0	Joaquín Sabina
296	A Tu Manera.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H	0	Junior H
297	Clave Ali.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
298	Clikeando.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
299	Con Un Presidente.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
300	El Chachito Anda Alegre.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
301	Intro.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
302	La Vi Llorar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
303	Libros y Libretas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
304	No Me Pesa.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
305	Ojos Colorados.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
306	Rambo el Apodo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
307	Se Amerita.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
308	Tingo y Tango.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Junior H - Cruisin_ with Junior H	0	Junior H
309	En Esta Boca.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Kany Garcia	0	Kany Garcia
310	Muero.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Kany Garcia	0	Kany Garcia
311	CONTIGO.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\KAROL G	0	KAROL G
312	Mina Bandida.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Lary	0	Lary
313	CC (Remix).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\lil joujou	0	lil joujou
314	Cayman.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
315	Céu Lilás.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
316	Desliga.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
317	Deus Dará.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
318	Domingo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
319	Fases da Vida.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
320	Fé Pra Caminhar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
321	Malvada.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
322	Meio Exagerado.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
323	Mundo de Fantasia.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
324	Não Quero Mais.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
325	Peso da Coroa.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
326	Sunshine.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
327	Vibração.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\LK	0	LK
328	Si No Quieres No.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez	0	Luis R Conriquez
329	19 por los Radios.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
330	A Punta de Balazos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
331	Aquellos Botones.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
332	Arre Pues.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
333	Bélicos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
334	El 27.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
335	El Agujero.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
336	El Ocho.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
337	Fresas Con Crema.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
338	Gorras Numeradas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
339	La Belikiza.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
340	La Supuesta Cita.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
341	Las Dos R.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
342	LMV.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
343	Mi Bello Ángel.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
344	Más Perrón Con los Balenciaga.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
345	Nemesio.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
346	Pixelados.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
347	Por Reynosa.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
348	Pónganse Bien.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
349	Quién Es Iván.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
350	Saquen Cuentas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
351	Sin Tanto Royo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV	0	Luis R Conriquez
352	Al Servicio.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
353	El 2.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
354	El Barbón (El Phoenix).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
355	El Menos Visto.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
356	GTA.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
357	La 701.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
358	Marinelas.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
359	Todo Bien.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
360	Un Joven Con Talento.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Luis R Conriquez - Corridos Bélicos, Vol. IV (Versión Deluxe)	0	Luis R Conriquez
361	Vas a Destrozarme (Versión Eden Muñoz).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Mau y Ricky	0	Mau y Ricky
362	Cheio de Fé.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\MC Marks	0	MC Marks
363	40 Años Y Contando.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
364	Agasajaba La Noche.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
365	Como No Quererte.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
366	El Alfa.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
367	Ismael Pa’ Servirle.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
368	Me Pego La Gana.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
369	Me Siento Borracho.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
370	Si Fueras Importante.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
371	Sorry Pa’ Los Gabachos.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
372	Suerte He Tenido.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
373	Y Apoco Crees.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
374	Y Van A Hablar.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Panter Bélico - De Buena Cepa	0	Panter Bélico
375	100_ Mexicano.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Pepe Aguilar - Celebrando a México	0	Pepe Aguilar
376	El Barzón.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Pepe Aguilar - Celebrando a México	0	Pepe Aguilar
377	La Charreada.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Pepe Aguilar - Celebrando a México	0	Pepe Aguilar
378	Popurrí Flor Silvestre (Mi Destino Fue Quererte _ Cielo Rojo _ La Basurita).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Pepe Aguilar - Celebrando a México	0	Pepe Aguilar
379	Popurrí José Alfredo Jiménez (El Rey _ Ella).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Pepe Aguilar - Celebrando a México	0	Pepe Aguilar
380	Un Puño de Tierra.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Pepe Aguilar - Celebrando a México	0	Pepe Aguilar
381	A Tu Manera.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Peso Pluma	0	Peso Pluma
382	NO SON KLLE.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Peso Pluma	0	Peso Pluma
383	Bandido.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Piso 21	0	Piso 21
384	CLI CLAN (Remix).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Potencia Lirical	0	Potencia Lirical
385	Poetas no Topo 3.2_ Enredo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Raillow	0	Raillow
386	dEsANiMaO _(.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ramoncito Vega	0	Ramoncito Vega
387	Pólvora de Ayer.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Residente	0	Residente
388	De la Ilusión Al Miedo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
389	El Bobo (Acústico).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
390	El Bobo.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
391	El Flechazo y la Secuela.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
392	Ella Sabe.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
393	Fluye.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
394	No Cambia Nada.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
395	Penthouse.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
396	Yo Me Vi (Autorretrato).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona	0	Ricardo Arjona
397	A Dónde Va el Amor.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona - Negro	0	Ricardo Arjona
398	En Vida.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona - Negro	0	Ricardo Arjona
399	Inventario.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona - Negro	0	Ricardo Arjona
400	Mal Por Ti.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona - Negro	0	Ricardo Arjona
401	Me Quedaré.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona - Negro	0	Ricardo Arjona
402	Solo Pienso en Ti.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricardo Arjona - Negro	0	Ricardo Arjona
403	Fuego de Noche, Nieve de Día.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Ricky Martin	0	Ricky Martin
404	NO SON KLLE.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Santa Fe Klan	0	Santa Fe Klan
405	Invítame A Un Café (Steve Aoki & Deorro Remix).mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Steve Aoki	0	Steve Aoki
406	Invítame A Un Café.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Steve Aoki	0	Steve Aoki
407	COLMILLO.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Tainy	0	Tainy
408	Troca.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Thalia	0	Thalia
409	K-POP.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Travis Scott	0	Travis Scott
410	Mete Dança.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Tília	0	Tília
411	Señorita.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Wisin	0	Wisin
412	curita.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Young Miko	0	Young Miko
413	Young Miko_ Bzrp Music Sessions, Vol. 58.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Young Miko	0	Young Miko
414	Mi Eterno Amor Secreto.mp3	C:\\Users\\User\\Downloads\\Testing Music-20250531T202804Z-1-001\\Testing Music\\Yuridia	0	Yuridia
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: rockola_user
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20250525064226_InitialCreate	9.0.5
20250525071739_InitialCreate	9.0.5
20250601203503_AddPlaylistItem	9.0.5
\.


--
-- Name: Artists_ArtistId_seq; Type: SEQUENCE SET; Schema: public; Owner: rockola_user
--

SELECT pg_catalog.setval('public."Artists_ArtistId_seq"', 1, false);


--
-- Name: PlaylistItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: rockola_user
--

SELECT pg_catalog.setval('public."PlaylistItems_Id_seq"', 1, false);


--
-- Name: Songs_SongId_seq; Type: SEQUENCE SET; Schema: public; Owner: rockola_user
--

SELECT pg_catalog.setval('public."Songs_SongId_seq"', 1, false);


--
-- Name: Artists PK_Artists; Type: CONSTRAINT; Schema: public; Owner: rockola_user
--

ALTER TABLE ONLY public."Artists"
    ADD CONSTRAINT "PK_Artists" PRIMARY KEY ("ArtistId");


--
-- Name: PlaylistItems PK_PlaylistItems; Type: CONSTRAINT; Schema: public; Owner: rockola_user
--

ALTER TABLE ONLY public."PlaylistItems"
    ADD CONSTRAINT "PK_PlaylistItems" PRIMARY KEY ("Id");


--
-- Name: Songs PK_Songs; Type: CONSTRAINT; Schema: public; Owner: rockola_user
--

ALTER TABLE ONLY public."Songs"
    ADD CONSTRAINT "PK_Songs" PRIMARY KEY ("SongId");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: rockola_user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- PostgreSQL database dump complete
--

